# PyMOL MD binding site visualisation — PfDHFR-TS K1
# Representative equilibrated frames from 100 ns MD
# Kenneth Odoh Chidiebere — MSc Computational Drug Discovery
# Generated by Notebook 05c Cell 15
# Open PyMOL -> File -> Run Script -> md_binding_site_figures.pml

# ── Global display settings ──────────────────────────────
bg_color white
set ray_opaque_background, 1
set antialias, 2
set ray_shadows, 0
set depth_cue, 0
set cartoon_fancy_helices, 1
set cartoon_fancy_sheets, 1
set stick_radius, 0.18
set sphere_scale, 0.30
set label_size, 16
set label_color, black
set label_font_id, 7

# ── CNP0286261_0 (rep frame 93.4 ns) ──────────────────

load C:/my_projects_all/portfolio_projects/Msc_project/figures/binding_site/md_frames/CNP0286261_0_md_rep_frame.pdb, complex_CNP0286261_0

select protein_CNP0286261_0, complex_CNP0286261_0 and polymer.protein
select ligand_CNP0286261_0, complex_CNP0286261_0 and resname UNL

hide everything, complex_CNP0286261_0
show cartoon, protein_CNP0286261_0
color gray85, protein_CNP0286261_0
set cartoon_transparency, 0.4, protein_CNP0286261_0
select bs_CNP0286261_0, protein_CNP0286261_0 and byres (ligand_CNP0286261_0 around 5.0)
show lines, bs_CNP0286261_0
color gray50, bs_CNP0286261_0
hide hydrogens, bs_CNP0286261_0
select key_CNP0286261_0, protein_CNP0286261_0 and resi 154+101
show sticks, key_CNP0286261_0
color gray40, key_CNP0286261_0
hide hydrogens, key_CNP0286261_0
select mut51_CNP0286261_0, protein_CNP0286261_0 and resi 51
show sticks, mut51_CNP0286261_0
color magenta, mut51_CNP0286261_0
hide hydrogens, mut51_CNP0286261_0
label mut51_CNP0286261_0 and name CA, '%s%s' % (resn, resi)
select mut59_CNP0286261_0, protein_CNP0286261_0 and resi 59
show sticks, mut59_CNP0286261_0
color magenta, mut59_CNP0286261_0
hide hydrogens, mut59_CNP0286261_0
label mut59_CNP0286261_0 and name CA, '%s%s' % (resn, resi)
select mut108_CNP0286261_0, protein_CNP0286261_0 and resi 108
show sticks, mut108_CNP0286261_0
color magenta, mut108_CNP0286261_0
hide hydrogens, mut108_CNP0286261_0
label mut108_CNP0286261_0 and name CA, '%s%s' % (resn, resi)
select mut164_CNP0286261_0, protein_CNP0286261_0 and resi 164
show sticks, mut164_CNP0286261_0
color magenta, mut164_CNP0286261_0
hide hydrogens, mut164_CNP0286261_0
label mut164_CNP0286261_0 and name CA, '%s%s' % (resn, resi)
show sticks, ligand_CNP0286261_0
color orange, ligand_CNP0286261_0
show spheres, ligand_CNP0286261_0 and name O+N
hide hydrogens, ligand_CNP0286261_0
center ligand_CNP0286261_0
zoom ligand_CNP0286261_0, 14
ray 1400, 1100
png C:/my_projects_all/portfolio_projects/Msc_project/figures/binding_site/fig22_CNP0286261_0_md_binding_site.png, dpi=300

delete complex_CNP0286261_0
delete protein_CNP0286261_0
delete ligand_CNP0286261_0
delete bs_CNP0286261_0
delete key_CNP0286261_0
delete mut51_CNP0286261_0
delete mut59_CNP0286261_0
delete mut108_CNP0286261_0
delete mut164_CNP0286261_0

# ── CNP0275186_1 (rep frame 98.3 ns) ──────────────────

load C:/my_projects_all/portfolio_projects/Msc_project/figures/binding_site/md_frames/CNP0275186_1_md_rep_frame.pdb, complex_CNP0275186_1

select protein_CNP0275186_1, complex_CNP0275186_1 and polymer.protein
select ligand_CNP0275186_1, complex_CNP0275186_1 and resname UNL

hide everything, complex_CNP0275186_1
show cartoon, protein_CNP0275186_1
color gray85, protein_CNP0275186_1
set cartoon_transparency, 0.4, protein_CNP0275186_1
select bs_CNP0275186_1, protein_CNP0275186_1 and byres (ligand_CNP0275186_1 around 5.0)
show lines, bs_CNP0275186_1
color gray50, bs_CNP0275186_1
hide hydrogens, bs_CNP0275186_1
select key_CNP0275186_1, protein_CNP0275186_1 and resi 54+160+154
show sticks, key_CNP0275186_1
color gray40, key_CNP0275186_1
hide hydrogens, key_CNP0275186_1
select mut51_CNP0275186_1, protein_CNP0275186_1 and resi 51
show sticks, mut51_CNP0275186_1
color magenta, mut51_CNP0275186_1
hide hydrogens, mut51_CNP0275186_1
label mut51_CNP0275186_1 and name CA, '%s%s' % (resn, resi)
select mut59_CNP0275186_1, protein_CNP0275186_1 and resi 59
show sticks, mut59_CNP0275186_1
color magenta, mut59_CNP0275186_1
hide hydrogens, mut59_CNP0275186_1
label mut59_CNP0275186_1 and name CA, '%s%s' % (resn, resi)
select mut108_CNP0275186_1, protein_CNP0275186_1 and resi 108
show sticks, mut108_CNP0275186_1
color magenta, mut108_CNP0275186_1
hide hydrogens, mut108_CNP0275186_1
label mut108_CNP0275186_1 and name CA, '%s%s' % (resn, resi)
select mut164_CNP0275186_1, protein_CNP0275186_1 and resi 164
show sticks, mut164_CNP0275186_1
color magenta, mut164_CNP0275186_1
hide hydrogens, mut164_CNP0275186_1
label mut164_CNP0275186_1 and name CA, '%s%s' % (resn, resi)
show sticks, ligand_CNP0275186_1
color tv_red, ligand_CNP0275186_1
show spheres, ligand_CNP0275186_1 and name O+N
hide hydrogens, ligand_CNP0275186_1
center ligand_CNP0275186_1
zoom ligand_CNP0275186_1, 14
ray 1400, 1100
png C:/my_projects_all/portfolio_projects/Msc_project/figures/binding_site/fig22_CNP0275186_1_md_binding_site.png, dpi=300

delete complex_CNP0275186_1
delete protein_CNP0275186_1
delete ligand_CNP0275186_1
delete bs_CNP0275186_1
delete key_CNP0275186_1
delete mut51_CNP0275186_1
delete mut59_CNP0275186_1
delete mut108_CNP0275186_1
delete mut164_CNP0275186_1

# ── CNP0539885_2 (rep frame 89.0 ns) ──────────────────

load C:/my_projects_all/portfolio_projects/Msc_project/figures/binding_site/md_frames/CNP0539885_2_md_rep_frame.pdb, complex_CNP0539885_2

select protein_CNP0539885_2, complex_CNP0539885_2 and polymer.protein
select ligand_CNP0539885_2, complex_CNP0539885_2 and resname UNL

hide everything, complex_CNP0539885_2
show cartoon, protein_CNP0539885_2
color gray85, protein_CNP0539885_2
set cartoon_transparency, 0.4, protein_CNP0539885_2
select bs_CNP0539885_2, protein_CNP0539885_2 and byres (ligand_CNP0539885_2 around 5.0)
show lines, bs_CNP0539885_2
color gray50, bs_CNP0539885_2
hide hydrogens, bs_CNP0539885_2
select key_CNP0539885_2, protein_CNP0539885_2 and resi 54+154+98+44
show sticks, key_CNP0539885_2
color gray40, key_CNP0539885_2
hide hydrogens, key_CNP0539885_2
select mut51_CNP0539885_2, protein_CNP0539885_2 and resi 51
show sticks, mut51_CNP0539885_2
color magenta, mut51_CNP0539885_2
hide hydrogens, mut51_CNP0539885_2
label mut51_CNP0539885_2 and name CA, '%s%s' % (resn, resi)
select mut59_CNP0539885_2, protein_CNP0539885_2 and resi 59
show sticks, mut59_CNP0539885_2
color magenta, mut59_CNP0539885_2
hide hydrogens, mut59_CNP0539885_2
label mut59_CNP0539885_2 and name CA, '%s%s' % (resn, resi)
select mut108_CNP0539885_2, protein_CNP0539885_2 and resi 108
show sticks, mut108_CNP0539885_2
color magenta, mut108_CNP0539885_2
hide hydrogens, mut108_CNP0539885_2
label mut108_CNP0539885_2 and name CA, '%s%s' % (resn, resi)
select mut164_CNP0539885_2, protein_CNP0539885_2 and resi 164
show sticks, mut164_CNP0539885_2
color magenta, mut164_CNP0539885_2
hide hydrogens, mut164_CNP0539885_2
label mut164_CNP0539885_2 and name CA, '%s%s' % (resn, resi)
show sticks, ligand_CNP0539885_2
color blue, ligand_CNP0539885_2
show spheres, ligand_CNP0539885_2 and name O+N
hide hydrogens, ligand_CNP0539885_2
center ligand_CNP0539885_2
zoom ligand_CNP0539885_2, 14
ray 1400, 1100
png C:/my_projects_all/portfolio_projects/Msc_project/figures/binding_site/fig22_CNP0539885_2_md_binding_site.png, dpi=300

delete complex_CNP0539885_2
delete protein_CNP0539885_2
delete ligand_CNP0539885_2
delete bs_CNP0539885_2
delete key_CNP0539885_2
delete mut51_CNP0539885_2
delete mut59_CNP0539885_2
delete mut108_CNP0539885_2
delete mut164_CNP0539885_2

# ── pyrimethamine (rep frame 38.7 ns) ─────────────────

load C:/my_projects_all/portfolio_projects/Msc_project/figures/binding_site/md_frames/pyrimethamine_md_rep_frame.pdb, complex_pyrimethamine

select protein_pyrimethamine, complex_pyrimethamine and polymer.protein
select ligand_pyrimethamine, complex_pyrimethamine and resname UNL

hide everything, complex_pyrimethamine
show cartoon, protein_pyrimethamine
color gray85, protein_pyrimethamine
set cartoon_transparency, 0.4, protein_pyrimethamine
select bs_pyrimethamine, protein_pyrimethamine and byres (ligand_pyrimethamine around 5.0)
show lines, bs_pyrimethamine
color gray50, bs_pyrimethamine
hide hydrogens, bs_pyrimethamine
select key_pyrimethamine, protein_pyrimethamine and resi 98+97+101+40
show sticks, key_pyrimethamine
color gray40, key_pyrimethamine
hide hydrogens, key_pyrimethamine
select mut51_pyrimethamine, protein_pyrimethamine and resi 51
show sticks, mut51_pyrimethamine
color magenta, mut51_pyrimethamine
hide hydrogens, mut51_pyrimethamine
label mut51_pyrimethamine and name CA, '%s%s' % (resn, resi)
select mut59_pyrimethamine, protein_pyrimethamine and resi 59
show sticks, mut59_pyrimethamine
color magenta, mut59_pyrimethamine
hide hydrogens, mut59_pyrimethamine
label mut59_pyrimethamine and name CA, '%s%s' % (resn, resi)
select mut108_pyrimethamine, protein_pyrimethamine and resi 108
show sticks, mut108_pyrimethamine
color magenta, mut108_pyrimethamine
hide hydrogens, mut108_pyrimethamine
label mut108_pyrimethamine and name CA, '%s%s' % (resn, resi)
select mut164_pyrimethamine, protein_pyrimethamine and resi 164
show sticks, mut164_pyrimethamine
color magenta, mut164_pyrimethamine
hide hydrogens, mut164_pyrimethamine
label mut164_pyrimethamine and name CA, '%s%s' % (resn, resi)
show sticks, ligand_pyrimethamine
color forest, ligand_pyrimethamine
show spheres, ligand_pyrimethamine and name O+N
hide hydrogens, ligand_pyrimethamine
center ligand_pyrimethamine
zoom ligand_pyrimethamine, 14
ray 1400, 1100
png C:/my_projects_all/portfolio_projects/Msc_project/figures/binding_site/fig22_pyrimethamine_md_binding_site.png, dpi=300

delete complex_pyrimethamine
delete protein_pyrimethamine
delete ligand_pyrimethamine
delete bs_pyrimethamine
delete key_pyrimethamine
delete mut51_pyrimethamine
delete mut59_pyrimethamine
delete mut108_pyrimethamine
delete mut164_pyrimethamine

quit